import Head from "next/head";
// import Link from "next/link";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import "dotenv/config";

import { getDatabase } from "../src/database";

export const getServerSideProps: GetServerSideProps = async () => {
  const mongodb = await getDatabase();

  const actors = await mongodb.db().collection("actors").find().toArray();

  return {
    props: {
      actors: actors,
    },
  };
};

export default function Home({ actors }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dynamic routing next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <nav> </nav>
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Dynamic routing</h1>
        <br />
        <p className={styles.description}>
          Bienvenue sur la page web consacré au travail sur : Dynamic routing
          next app.
          <code className={styles.code}></code>
        </p>
        <div>
          <p>Element qui s'affiche provenant de la DB :</p>
          <p>{actors}</p>
        </div>
      </main>
      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{" Kevin"}
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
}
